FROM node:alpine AS builder

WORKDIR /build

COPY ./producer/package*.json ./

RUN npm install

COPY ./producer ./

RUN npm run build

FROM node:alpine

WORKDIR /app

COPY --from=builder ./build/package*.json ./
COPY --from=builder ./build/dist ./dist
COPY --from=builder ./build/node_modules ./node_modules

# RUN apk add --update nodejs npm

EXPOSE 5000

CMD ["npm", "run", "start"]