# format log untuk logging
log_format main '$remote_addr - [$time_local] '
                    '"$request" "code: $status" "bytes: $body_bytes_sent" '
                    '"$http_referer" "$http_user_agent" '
                    '"$http_x_forwarded_for" '
                    'rt=$request_time urt=$upstream_response_time '
                    'proto=$scheme';

server {
    # hapus semua 'default_server' pada directives "listen" dan biarkan semua listen ke 80
    listen 80;
    listen [::]:80;

    # hapus directives "root" dan "index"

    # ubah "server_name" sesuai dengan domain
    # contoh: server_name be.pemilos.com
    server_name be.example.com;

    access_log /var/log/nginx/access.log main;

    location / {
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        # reverse proxy ke 5000 karena app aktif pada port 5000
        proxy_pass http://localhost:5000;
    }
}