# editlah bagian yang ada pada file ini
server {
    # hapus semua 'default_server' pada directives "listen" dan biarkan semua listen ke 80
    listen 80;
    listen [::]:80;

    # hapus directives "root" dan "index"

    # ubah "server_name" sesuai dengan domain
    # contoh: server_name grafana.pemilos.com
    server_name grafana.example.com;

    access_log off;

    location / {
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        # reverse proxy ke 3000 karena grafana aktif pada port 3000
        proxy_pass http://localhost:3000;
    }
}