user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format main '$remote_addr - [$time_local] '
                    '"$request" "code: $status" "bytes: $body_bytes_sent" '
                    '"$http_referer" "$http_user_agent" '
                    '"$http_x_forwarded_for" '
                    'rt=$request_time urt=$upstream_response_time '
                    'proto=$scheme';

    access_log  /var/nginx/log/access.log  main;

    sendfile        on;
    keepalive_timeout  65;

    # Edit hanya pada blok 'server' aja kecuali kamu tau betul apa yang sedang kamu lakukan
    server {
        listen 80;

        location / {
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://app:5000;
        }
    }
}