{
 "title": "Pemilom",
 "tags": [ "linux" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\", nodename=\"$nodename\"}, instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  { "title": "Quick CPU / Mem / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pressure",
   "type": "bargauge",
   "description": "Resource pressure via PSI",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_pressure_cpu_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "CPU"
    },
    {
     "expr": "irate(node_pressure_memory_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Mem"
    },
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "I/O"
    },
    {
     "expr": "irate(node_pressure_irq_stalled_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Irq"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Sys Load",
   "type": "gauge",
   "description": "System load  over all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{instance=\"$node\",job=\"$job\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Real RAM usage excluding cache and reclaimable memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"$node\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$node\", job=\"$job\"})) * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Percentage of swap space currently used by the system",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"})) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"}\n   - node_filesystem_avail_bytes{instance=\"$node\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"})\n  / node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"}\n) * 100\n"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reboot Required",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_reboot_required{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Basic CPU / Mem / Net / Disk (Node Exporter)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "CPU time spent busy vs idle, split by activity type",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=~\".*irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",  mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "RAM and swap usage overview, including caches",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "Swap used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Per-interface network traffic (receive and transmit) in bits per second",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "Rx {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "Tx {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Percentage of filesystem space used for each mounted device",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", device!~\"rootfs\"} - node_filesystem_avail_bytes{instance=\"$node\", job=\"$job\", device!~\"rootfs\"}) / node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", device!~\"rootfs\"}) * 100",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Mongo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "MongoService UP",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_up{job=~\"mongo\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "stat",
   "description": "The number of incoming connections from clients to the database server. This number includes the current shell session. Consider the value of connections.available to add more context to this datum.",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{job=\"mongo\", conn_type=\"current\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mongodb Uptime",
   "type": "stat",
   "description": "Mongodb Service Uptime in hours",
   "gridPos": { "h": 8, "w": 4, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_instance_uptime_seconds{job=\"mongo\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Created Connections",
   "type": "stat",
   "description": "Count of all incoming connections created to the server. This number includes connections that have since closed.",
   "gridPos": { "h": 8, "w": 3, "x": 11, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{job=\"mongo\", conn_type=\"totalCreated\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "description": "The number of active client connections to the server. Active client connections refers to client connections that currently have operations in progress.",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{job=\"mongo\", conn_type=\"available\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "stat",
   "description": "The number of unused incoming connections available. Consider this value in combination with the value of connections.current to understand the connection load on the database, and the UNIX ulimit Settings document for more information about system thresholds on available connections.",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{job=\"mongo\", conn_type=\"available\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Collections/DB",
   "type": "state-timeline",
   "description": "Number of collections in the database.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "mongodb_dbstats_collections{job=\"mongo\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{job=~\"mongo\"}[$__interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Allocated Storage to Collections in DB",
   "type": "timeseries",
   "description": "Sum of the space allocated to all collections in the database for document storage, including free space.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mongodb_dbstats_storageSize{job=\"mongo\"}",
     "legendFormat": "{{database}} "
    }
   ]
  },
  { "title": "Access Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "New Panel",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "{job=\"nginx\"} |= ``"
    }
   ]
  }
 ]
}