global:
  scrape_interval: 15s

scrape_configs:
  # sesuaikan host dan port sesuai yang ada di docker compose
  # disarankan untuk tidak mengganti value `job_name` karena nanti akan ada misconfig pada grafana dashboard
  # kalo dah dikasi tau jan ngeyel ya dek ya
  - job_name: node_exporter
    static_configs:
      - targets: ["node_exporter:9100"]
  - job_name: mongo
    static_configs:
      - targets: ["mongodb_exporter:9216"]